import 'dart:async';
import 'dart:io';

import 'package:connectycube_sdk/connectycube_chat.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:gaya/routing/getx_route_methods.dart';
import 'package:get/get.dart';

import '../../controller/crowns_controller.dart';
import '../../utils/logger.dart';
import 'fcm_service.dart';
import 'navigation_utils.dart';
import 'notification_routes.dart';

class FCMListeners {
  FCMListeners._();

  static late FirebaseMessaging _firebaseMessagingInstance;
  static late MyLoggerServices logger;
  static FCMListeners? _listeners;
  bool _areListenersRegistered = false;

  factory FCMListeners.init() {
    _firebaseMessagingInstance = FirebaseMessaging.instance;
    logger = MyLoggerServices.to;
    return _listeners ??= FCMListeners._();
  }

  StreamSubscription? _onMessageSubscription;
  StreamSubscription? _onMessageOpenedAppSubscription;

  /// Start listening to new FCM messages and handle them
  void startListeningToNewMessages() {
    if (_areListenersRegistered) return;
    _areListenersRegistered = true;
    logger.print('startListeningToNewMessages');

    /// 1. This method only call when App in background it mean app must be closed
    _onInitialMessage();

    /// Register listeners
    _registerListeners();
  }

  ///
  /// Workaround for FCM messages to avoid multiple listeners on the same stream
  /// Case: When multiple streams are listening, the app opens screen multiple times (for each listener)
  /// <Happening when app is in background and user clicks on FCM notification>
  /// *Solution*: Unregister listeners before registering new ones (if any)
  ///

  void _registerListeners() {
    _unregisterListeners();

    /// 2. This method only call when App in foreground it mean app must be opened
    _onMessageSubscription = FirebaseMessaging.onMessage.listen((message) async {
      logger.print('_onMessageSubscription: ${message.toMap()}');
      bool shouldNotify = true;
      bool isChatMessage = false;
      if (message.notification != null) {
        /*     /// watcher for in app notification - to perform actions on in app notification
          InAppNotificationWatcher.instance.watchInAppNotification(message);*/
        Map<String, String>? newPayload;
        if (message.data['payload'] != null) {
          final myPayload = message.data['payload'];

          newPayload = NotificationNavigationService.getPayload(payload: myPayload);
          isChatMessage = newPayload?["messageType"] == "chatMessage";
          bool isPost = newPayload?["messageType"] == "post";
          if (isChatMessage && Get.currentRoute == RouteHelper.personMessage) {
            shouldNotify = false;
          } else if (isPost && Get.currentRoute == RouteHelper.commentWithPostScreen) {
            shouldNotify = false;
          }
        } else if (message.data['dialog_id'] != null) {
          isChatMessage = true;

          /// check if notification is of group chat, we don't show notification for group chat if generated by CC itself.
          /// As offline notification is sometimes generated by CC itself [RARE] so we are also generating so it might
          /// get duplicate FCMs so for that reason, we are showing group notification only if it is generated by user.
          /// if it is generated by CC then we are not showing notification. It can be identified by is_group_notification key.
          /// if is_group_notification key is present then it is generated by user. If not then it is generated by CC.
          ///
          /// This will work only for android, for iOS, [stopIOSAlerts] is used to stop showing notification for group chat.
          if (message.data["dialog_type"] == CubeDialogType.PUBLIC && message.data["is_group_notification"] == null) {
            shouldNotify = false;
          }
          newPayload = {
            "user_id": message.data["user_id"] ?? '123',
            "dialog_type": message.data["dialog_type"] ?? 'Message',
            "title": message.data["title"] ?? '',
            "dialog_id": message.data["dialog_id"] ?? '123',
            "message_id": message.data["message_id"] ?? '132',
            "message": message.data["message"] ?? '',
            "messageType": "chatMessage",
          };
          if (Get.currentRoute == RouteHelper.conversation) {
            shouldNotify = false;
          }
        }

        /// if user open app from notification and it is a crown notification then update the user crowns
        if (message.notification?.title?.contains("crowns, use them now!") ?? false) {
          CrownsController.to.updateCurrentUser();
        }
        if (Platform.isAndroid && shouldNotify) {
          FirebaseMessagingService.showNotification(message);
        }
      }
    });

    // /// 3. This method only call when App in background and not terminated(not closed)
    _onMessageOpenedAppSubscription = FirebaseMessaging.onMessageOpenedApp.listen((message) async {
      logger.print('_onMessageOpenedAppSubscription: $message');
      onRemoteMessage(message);
    });

    logger.print('Listeners registered!');
  }

  /// Unregister all listeners
  _unregisterListeners() {
    _onMessageSubscription?.cancel();
    _onMessageOpenedAppSubscription?.cancel();
  }

  _onInitialMessage() {
    _firebaseMessagingInstance.getInitialMessage().then((message) {
      logger.print('getInitialMessage: $message');
      if (message != null) {
        onRemoteMessage(message);
      }
    });
  }

  __handlePayloadMessage(RemoteMessage remote) {
    final payload = remote.data;
    try {
      final notification = PayloadNotification.fromJson(payload);

      /// Show Chat Message only if current screen is not conversation
      if (notification.isMessageNotification) {
        /// no need to show notification if conversation is open
        if (notification.isConversationViewOpen) return;
        FirebaseMessagingService.showNotification(remote);
        return;
      }

      FirebaseMessagingService.showNotification(remote);
    } catch (e) {
      logger.print(e);
    }
  }

  /// Use for Intial &  onMessageOpened.
  onRemoteMessage(RemoteMessage message) {
    if (message.data.isNotEmpty) {
      Map<String, String>? newPayload;

      /// rest of the cases for notification
      if (message.data['payload'] != null) {
        newPayload = NotificationNavigationService.getPayload(payload: message.data['payload']);
        NotificationApiController.navigate(newPayload?["messageType"], newPayload);
      }

      /// case message
      else if (message.data['dialog_id'] != null) {
        newPayload = {
          "user_id": message.data["user_id"] ?? '123',
          "dialog_type": message.data["dialog_type"] ?? 'Message',
          "title": message.data["title"] ?? '',
          "dialog_id": message.data["dialog_id"] ?? '123',
          "message_id": message.data["message_id"] ?? '132',
          "message": message.data["message"] ?? '',
          "messageType": "chatMessage",
        };
        NotificationApiController.navigate(newPayload["messageType"], newPayload);
      }
    }
  }
}

enum ConnectyCubeNotification { ChatMessage, Unknown }

class PayloadNotification {
  final String title;
  final String body;
  final String dialogId;
  final String dialogType;
  final ConnectyCubeNotification messageType;
  final String userId;

  PayloadNotification({
    required this.title,
    required this.body,
    required this.dialogId,
    required this.dialogType,
    required this.messageType,
    required this.userId,
  });

  factory PayloadNotification.fromJson(Map<String, dynamic> json) {
    return PayloadNotification(
      title: json['title'],
      body: json['message'],
      dialogId: json['dialog_id'],
      dialogType: json['dialog_type'],
      messageType: parse(json['messageType']),
      userId: json['user_id'],
    );
  }

  Map<String, String> toJson() => {
        'title': title,
        'body': body,
        'dialog_id': dialogId,
        'dialog_type': dialogType,
        'messageType': reverseParse(messageType),
        'user_id': userId,
      };

  static ConnectyCubeNotification parse(String type) {
    switch (type) {
      case "chatMessage":
        return ConnectyCubeNotification.ChatMessage;
      default:
        return ConnectyCubeNotification.Unknown;
    }
  }

  static String reverseParse(ConnectyCubeNotification type) {
    switch (type) {
      case ConnectyCubeNotification.ChatMessage:
        return "chatMessage";

      default:
        return ConnectyCubeNotification.Unknown.name;
    }
  }
}

extension NotifictationHelper on PayloadNotification {
  bool get isMessageNotification => messageType == ConnectyCubeNotification.ChatMessage;

  bool get isConversationViewOpen => Get.currentRoute.toLowerCase() == RouteHelper.conversation.toLowerCase();

  bool get getCanShowNotification => isMessageNotification && isConversationViewOpen;

  bool get isGroupNotification => dialogType == CubeDialogType.PUBLIC.toString() || dialogType == CubeDialogType.PUBLIC;

  bool get isPrivateNotification => dialogType == CubeDialogType.PRIVATE.toString() || dialogType == CubeDialogType.PRIVATE;
}
